@extends('layouts.public')
@section('content')
    <h1>Welcome to the Home Page</h1>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <h1>Welcome to the Home Page</h1>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <h1>Welcome to the Home Page</h1>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <h1>Welcome to the Home Page</h1>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <h1>Welcome to the Home Page</h1>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <h1>Welcome to the Home Page</h1>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    <p>This is a simple home page.</p>
    
@stop
